FROM golang:1.24.0 AS build

COPY *.go go.mod go.sum memuse.c memuse.h /go/

RUN go test && \
    go build

FROM gcr.io/distroless/base-debian12:nonroot

WORKDIR /memuse
COPY --chown=nonroot --from=build /go/memuse memuse

ENTRYPOINT [ "./memuse" ]