FROM golang:1.24.0 AS build

COPY *.go go.mod go.sum memuse.c memuse.h /go/

RUN go test && \
    go build

FROM ubuntu:24.04

RUN apt-get update && \
    apt-get install --no-install-recommends -y adduser && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN adduser memuse -u 11000
USER 11000

WORKDIR /memuse
COPY --chown=memuse --from=build /go/memuse memuse

ENTRYPOINT [ "./memuse" ]