name: C
on:
  push:
    branches: [ master ]
    paths-ignore:
      - README.md
      - ubuntu.yaml
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 2
    strategy:
      matrix:
        platform:
          - name: ubuntu-latest
            os: ubuntu-latest
          - name: macos-latest
            os: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: DEBUG Configure CMake
        run: cmake -B ${{github.workspace}}/build "-DCMAKE_BUILD_TYPE=Debug"
      - name: DEBUG Build
        run: cmake --build ${{github.workspace}}/build
      - name: DEBUG Test
        run: ctest --verbose --timeout 60
        working-directory: ${{github.workspace}}/build
      - name: DEBUG Run - allocation
        run: ./memuse -c '1:1|2:1|3:1'
        working-directory: ${{github.workspace}}/build
      - name: Clean
        run: rm -rf ${{github.workspace}}/build
      - name: RELEASE Configure CMake
        run: cmake -B ${{github.workspace}}/build "-DCMAKE_BUILD_TYPE=Release"
      - name: RELEASE Build
        run: cmake --build ${{github.workspace}}/build
      - name: RELEASE Run - help
        run: ./memuse -h
        working-directory: ${{github.workspace}}/build
      - name: RELEASE Run - allocation
        run: ./memuse -c '1:1|2:1|3:1'
        working-directory: ${{github.workspace}}/build