name: Go
on:
  push:
    branches: [ master ]
    paths-ignore:
      - ".github/dependabot.yml"
      - '.*ignore'
      - 'Dockerfile-*'
      - 'LICENSE'
      - '*.md'
      - '*.yaml'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 2
    strategy:
      matrix:
        platform:
          - name: ubuntu-latest
            os: ubuntu-latest
          - name: macos-latest
            os: macos-latest
    steps:
      - name: OS info
        run: |
          uname -a
          ulimit -l
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.0'
      - name: Build
        run: go build
      - name: Test
        run: go test
      - name: Integration tests
        run: ./integration-tests.sh