name: memuse
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 2
    strategy:
      matrix:
        platform:
          - name: ubuntu-latest
            os: ubuntu-latest
          - name: macos-latest
            os: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest
      - name: Run - help
        working-directory: ${{github.workspace}}/build
        run: ./memuse -h
      - name: Run - allocation
        working-directory: ${{github.workspace}}/build
        run: ./memuse -c '1:1|2:1|3:1'